export const BASE_URL_OLD = 'https://apps.appsmaventech.com/smuggler_backend/api/v1/user/'
export const IMAGE_UPLOAD_OLD = 'https://apps.appsmaventech.com/smuggler_backend/api/v1/superAdmin/uploadImage'
export const SOCKET_URL_OLD = 'wss://smuggler.appsmaventech.com/'



export const IMAGE_BASE_URL = 'https://d8ge8ja4zvdsk.cloudfront.net/'
export const SOCKET_URL = 'https://api.mysmugglers.com'
export const DEV_SERVER_URL = 'https://dev-api.mysmugglers.com/api/v1/user/'
export const PROD_BASE_URL = 'https://api.mysmugglers.com/api/v1/user/'
export const BASE_URL = PROD_BASE_URL

export const USER_SIGNUP = BASE_URL+'userRegister'
export const SEND_OTP = BASE_URL+'userSendOtp'
export const VERIFY_OTP = BASE_URL+'userVerifyOtp'
export const USER_LOGIN = BASE_URL+'userLogin'
export const GOOGLE_LOGIN = BASE_URL+'userGoogleRegister'
export const FB_LOGIN = BASE_URL+'userFacebookRegister'
export const APPLE_LOGIN = BASE_URL+'userAppleRegister'
export const FORGOT_PASSWORD = BASE_URL+'userForgotPassword'
export const LOGOUT = BASE_URL+'userLogout'
export const IMAGE_UPLOAD = 'https://api.mysmugglers.com/api/v1/superAdmin/uploadImage'
export const UPDATE_PROFILE = BASE_URL+'userUpdateProfile'
export const GET_PROFILE = BASE_URL+'userGetProfile'
export const GET_SAVED_ADDRESS_LIST = BASE_URL+'userGetDeliveryAddresses'
export const GET_NOTIFICATIONS_LIST = BASE_URL+'userGetNotifications'
export const GET_HOME_SCREEN_DATA = BASE_URL+'userGetAllProducts'
export const GET_ALL_CATEGORIES = BASE_URL+'userGetAllCategories'
export const SEARCH_ALL = BASE_URL+'userSearch'
export const UPDATE_PROFILE_IMAGE = BASE_URL+'userUpdateProfileImage'
export const GET_PRODUCT_DETAIL = BASE_URL+'getProductDetail'
export const GET_DATA_CATEGORY_WISE = BASE_URL+'userGetAllProductsCategoryWise'
export const ADD_DELIVERY_ADDRESS = BASE_URL+'userAddDeliveryAddress'
export const GET_DELIVER_FEE = BASE_URL+'userGetDeliveryFee'
export const PLACE_ORDER = BASE_URL+'userGenerateOrder'
export const PLACE_ORDER_V2 = BASE_URL+'userGenerateOrderV2'
export const GET_ORDERS = BASE_URL+'userGetOrders'
export const GET_SINGLE_ORDER_DETAIL = BASE_URL+'userGetSingleOrderDetail'
export const APPLY_COUPON_CODE = BASE_URL+'userCheckDiscountCode'
//export const GET_FILTER_DATA = BASE_URL+'userGetAllProductsCategoryWiseAll'
export const GET_FILTER_DATA = BASE_URL+'userGetAllFilters'
export const GET_CATEGORY_DATA_OLD = BASE_URL+'userGetAllProductsCategoryWise'
export const GET_CATEGORY_DATA = BASE_URL+'userGetAllProductsCategoryWisePagination'
export const ADD_RATING = BASE_URL+'userAddRating'
export const CHANGE_PASSWORD = BASE_URL+'userUpdatePassword'
export const CHECK_ASAP_AND_TIME = BASE_URL+'userCheckASAPAndSchduleTime'
export const CHECK_SIZE_FOR_INVENTORY = BASE_URL+'userCheckSizeQuantityForInventory'
export const CHECK_SIZE_BEFORE_ORDER_PLACE = BASE_URL+'userCheckSizeQuantityBeforeOrderPlace'
export const GET_SECRET_CLIENT = BASE_URL+'userCreateClientSecret'



export const SET_DEFAULT_ADDRESS = BASE_URL+'userSetDeliveryAddressDefault'
export const UPDATE_DELIVERY_ADDRESS = BASE_URL+'userUpdateDeliveryAddress'
export const GET_SAVED_CARDS = BASE_URL+'userGetSavedCards'
export const DELETE_SAVED_ADDRESS = BASE_URL+'userDeleteDeliveryAddress'